### ISSUE TITLE
More Detailed Output

### ISSUE THREAD

**Issue by mconery** [getian107/SuSiEx#1]
Hi SuSiEx Team! We're really interested in using your method for a project we're working on, and we're wondering if it might be possible to get more detailed output from SuSiEx similar to what SuSiE gives. Specifically, we're interested in seeing a more detailed .cs files that has 'CS_PIP's for all variants and not just those in the credible sets. We would similarly like posterior means and log bayes factors for all the variants. We need these results for downstream analyses, and any help you can provide would be greatly appreciated.

**Comment by yorkklause** [comment]
Hi mconery,
We have recently released an updated version of SuSiEx, now implemented in C++. In this new version, we have included detailed output in the *snp file, which provides information such as the Probabilistic Inclusion Probability (PIP) and logarithm of Bayes factors for each variant and each credible set.
Kai

**Comment by mconery** [comment]
That's perfect! Thank you so much Kai!
