### ISSUE TITLE
"Less than X token were found in Line Y in summary statistics file F": are missing test statistics allowed?

### ISSUE THREAD

**Issue by cqgd** [getian107/SuSiEx#12]
Hi Kai, Tian,

Thanks a lot for your hard work on this -- that overview of cross-ancestry fine-mapping approaches in Fig. 1 of your preprint is great.

I'm getting [this error](https://github.com/getian107/SuSiEx/blob/b0da7826d2a68584223ca4ca52248a63e398cac0/src/data.cpp#L293-L295) while attempting to run SuSiEx:

"Error: Less than 14 token were found in Line 1 in summary statistics file sumstats_EUR.tsv" ,

followed by my first line of actual data (i.e. not the header of my summary statistics file). 

What might be the issue here? 

I suspect that missingness may play a role. The SNP on this first line, like a few others further down, has a valid name and position, but is missing association testing data: it has no beta, SE, pval etc.

I could remove all SNPs with missing data from my sumstats, but my understanding is that the LD matrices and sumstats need to have the same number of SNPs in the same order. Thus, I expect that if I remove the SNPs with missing test statistics, I will have to recalculate the LD matrices. This seems a little impractical when analyzing many traits with different patterns of missingness in their sumstats -- ideally I would like to re-use LD panels between analyses of different traits. 

I may have missed something in the above. Perhaps some missingness in the sumstats is fine. In that case, we're probably looking at a formatting error, and I'd appreciate it if you could point me in the right direction.

Could you comment on whether missing test statistics in the summary statistics are allowed or not (and if so, what formatting would be required)?

Many thanks,

Chris

**Comment by yorkklause** [comment]
Hi Chris,

Thank you for your comment!

In SuSiEx, we extract the intersection of variants from the summary statistics file and the LD matrices. Please remove variants with the missing beta, standard error, or p-value in your summary statistics. You can keep the LD matrices as they are.

My best

Kai Yuan

**Comment by cqgd** [comment]
Many thanks Kai,

That works! Out of curiosity: is running SuSiE-x for just one population (which also seems to work) equivalent to just using SuSiE?

Best wishes,

Chris

**Comment by yorkklause** [comment]
Hi Chris, 

Glad to hear it's working. Regarding your question, if you run SuSiEx with just one population, it's equivalent to running SuSiE.

My best

Kai Yuan

**Comment by chrise-23** [comment]
Great, thanks for your help Kai!
