### ISSUE TITLE
Full Out

### ISSUE THREAD

**Issue by osahonjeffery** [getian107/SuSiEx#16]
I am running the SuSiEx code, and anytime I use the --full_out=True command, my code stops running and come out with this complaint. 
"Segmentation fault (core dumped)"
Meanwhile, the code runs smoothly when I don't include this command.

**Comment by yorkklause** [comment]
Hi osahonjeffery,

Thank you for using our method!

I apologize for the software crash. I’m currently traveling but should have some time to address the issue, likely sometime next week.

My best

Kai Yuan

**Comment by yorkklause** [comment]
Hi osahonjeffery,

Apologies for the confusion! The --full_out parameter is no longer in use, but I hadn't updated the manual. In the current version, all SNP information is automatically outputted to the *.snp file by default. This file contains all SNPs included in the fine-mapping analysis.

If you attempt to use the --full_out=True option, SuSiEx will respond with:

> ./bin/SuSiEx: unrecognized option '--full_out=True'
> Cannot identify parameter ?

then followed by the help information.

Could you share the full log file here? I'd be happy to review it to ensure there are no other issues affecting your analysis.

My best

Kai Yuan
