### ISSUE TITLE
Question About SuSiEx Output and MESuSiE-like Functionality

### ISSUE THREAD

**Issue by goodluckncb** [getian107/SuSiEx#17]
Hello,

I am using SuSiEx and encountered the following output in a sample file:

| BP       | SNP                             | PIP(CS1)   | LogBF(CS1, Pop1) | LogBF(CS1, Pop2) |
|----------|---------------------------------|------------|------------------|------------------|
| 7591240  | rs12723148:7591240:G:A          | 0.995112   | 89.4683          | 17.4739          |

I would like to ask for clarification on a few points:
1. Do `LogBF(CS1, Pop1)` and `LogBF(CS1, Pop2)` represent the Bayes factors for this SNP in different populations?
2. Does `PIP(CS1)` reflect the posterior inclusion probability aggregated across populations?
3. Does SuSiEx have functionality similar to MESuSiE for obtaining population-specific and shared PIPs? For example, as described in the [Run_MESuSiE](https://borangao.github.io/meSuSie_Analysis/Run_MESuSiE.html) analysis.

Thank you very much for your help!

Kind regards,  
caibo

**Comment by yorkklause** [comment]
Hi caibo,

Thank you for using our method!

For your questions:

1. LogBF(CS1, Pop1) represents the sum of log Bayes factors across all causal configurations. For example, with two populations, there are 4 different causal configurations (a. Pop1 causal & Pop2 causal; b. Pop1 causal & Pop2 non-causal; c. Pop1 non-causal & Pop2 causal; d. Pop1 non-causal & Pop2 non-causal). 

LogBF(CS1, Pop1) = LogBF(CS1, config a + config b)
LogBF(CS1, Pop2) = LogBF(CS1, config a + config c)

2. Yes.

3. In our method, we use a different approach to determine whether a credible set is population-specific or shared. We rely on the posterior probability to infer this, which you can find in the ".summary" file under the "POST-HOC_PROB_POP" column. If this probability exceeds 0.8, we consider the set to manifest causal in that population.

My best

Kai Yuan

**Comment by goodluckncb** [comment]
Hi Kai,

Thank you very much for your prompt response and helpful explanations. I have a few additional questions and would greatly appreciate your insights.

The first question concerns the interpretation of the summary results. For instance, in the summary file:


| CS_ID | CS_LENGTH | CS_PURITY | MAX_PIP_SNP      | BP       | REF_ALLELE | ALT_ALLELE | REF_FRQ    | BETA          | SE           | -LOG10P      | MAX_PIP | POST-HOC_PROB_POP1 | POST-HOC_PROB_POP2 |
|-------|-----------|-----------|------------------|----------|------------|------------|------------|---------------|--------------|--------------|---------|---------------------|---------------------|
| 1     | 2         | 1         | 22:31028944:A:G | 31028944 | G,NA       | A,NA       | 0.8131,NA  | -0.00703411,NA | 0.00144111,NA | 5.97661,NA | 0.90398 | 1                   | 0.5                 |
| 2     | 2         | 1         | 22:31012673:G:A | 31012673 | A,NA       | G,NA       | 0.8131,NA  | 0.00653366,NA | 0.00144111,NA | 5.237,NA    | 0.893308 | 1                   | 0.5                 |

Can we assume that any CS appearing in the summary file includes a causal SNP with 95% probability if we set `--level=0.95`? Also, does this CS imply a causal association for the overall population? However, I’ve observed that some populations (e.g., POP1 or POP2) do not seem to show a causal association. Could this result from insufficient sample size in these populations?

Additionally, if a CS is absent in a specific region, does this indicate there is no population-specific CS there? For example, I also performed fine mapping with SuSiE (susieR) stratified by ethnicity (EUR, EAS), and found population-specific CSs in that region. How should I interpret this?

I also compared the results of SuSiEx and susieR and found that susieR identified more CSs, with most of these CSs having a length of one.

The second question concerns region selection. My research focuses on multi-ancestry meta-analysis for various cancers, with data from both European and Asian populations. I performed meta-analyses for European and Asian groups separately, and then used MR-MEGA for multi-ancestry meta-analysis. This process led to several questions:

1. Should I base fine-mapping regions on risk regions identified in European + Asian populations or also include MR-MEGA results?
2. Since not all cancers had SNPs reaching the p=5e-8 threshold, I used p=1e-6 as the threshold for lead SNPs to maintain consistency across analyses. Do you think this approach is valid? Could this explain why susieR identifies more CSs?
3. When comparing SuSiEx and susieR for the number of CSs detected, I used the same regions for both, which might have included non-significant regions for some populations (e.g., non-significant regions for Asians were used for fine-mapping in Asians). 

Thank you very much for your help!

**Comment by yorkklause** [comment]
Hi caibo,

Thank you for your questions!

For the first question, yes, --level=0.95 indicates that the probability of the identified credible set containing at least one causal SNP is 0.95 or higher. We used a post hoc probability to determine whether a credible set is causal in a given population. If the post hoc probability is greater than 0.8, we consider the credible set to be causal in that population.
In your example, both credible sets are specific to Pop1, as the post hoc probability is 1 in Pop1 but only 0.5 in Pop2. "NA" signifies that the variant is absent (MAF < 0.005) in that population.

For the additional question, "Additionally, if a CS is absent in a specific region, does this indicate there is no population-specific CS there? For example, I also performed fine mapping with SuSiE (susieR) stratified by ethnicity (EUR, EAS), and found population-specific CSs in that region. How should I interpret this?"
I didn't fully understand your question. Are you saying that you used SuSiEx for EUR+EAS analysis, and ran susieR separately for EUR and EAS? And that only one of the susieR analyses identified a credible set, which you then defined as a population-specific CS?

For this finding: "I also compared the results of SuSiEx and susieR and found that susieR identified more CSs, with most of these CSs having a length of one", I have a few questions:
1. When comparing the results of two fine-mapping analyses, how did you align credible sets across studies? For instance, if one credible set is shared between EUR and EAS, and SuSiEx and susieR (EUR) and susieR(EAS) identified this credible set, would you count this credible set twice for susieR and once for SuSiEx?
2. Did you use "in-sample" LD for both the SuSiEx and susieR analyses?
3. Did you apply the same p-value threshold to filter out credible sets that do not meet genome-wide significance?
4. Did you apply the same minor allele frequency filtering for SuSiEx and susieR?

Regarding your second question on loci definition, in our paper, we used a six-way LD clumping-based method to define candidate loci. The goal was to include as many candidate loci as possible in the analysis.
1. We suggest including regions that show genome-wide significance in MR-MEGA.
2. Using a significance threshold of p=1e-6 for lead variants is likely acceptable if this level of significance is standard in your field. I don’t believe this threshold explains why susieR identified more credible sets than SuSiEx.
3. Including non-significant loci should be fine. SuSiE series models are well-calibrated, so incorporating these loci is OK.

My best

Kai Yuan

**Comment by goodluckncb** [comment]
Hi Kai,

Thank you very much for your prompt reply. Over the past few days, I reanalyzed the results for colorectal cancer and found that SuSiEx detected a greater number of credible sets (CS) at 99% confidence and yielded shorter CS lengths. Here are the results:

- **SuSiEx**: `table(SuSiEx$CS_LENGTH)`

```
1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  19  20  21  22  23  25  26  27  28  29  32  33  34  35  36  37  38  39  40  50  52  58  68  73  75  76  82  86  95  96  99 106 111 113
42  22  16  20  12   4   7   6   4   4   4   3   2   4   5   1   5   3   4   2   2   2   3   2   1   1   2   1   1   2   1   1   1   1   1   2   1   1   1   2   1   1   1   2   1   1   1   1   1   1
```

- **susieR_EUR**: `table(susieR_EUR$cs_length)`

```
1   2   3   4   5   6   7   8   9  11  12  13  14  15  16  19  21  23  25  28  29
519  53  21   7   7   9   2   3   1   1   1   2   3   1   1   1   1   1   1   1   1
```

- **susieR_EAS**: `table(susieR_EAS$cs_length)`

```
1   2   3   4   5   6   7   8   9  10  11  12  13  14  16  17  19  28  33  35  38  41  80 115
236  40  14   8   4   3   4   6   4   2   1   2   1   1   1   1   1   1   1   1   1   1   1   1
```

Since most of my European and Asian meta-analysis data are derived from individual GWAS data, I used the 1000 Genomes as the LD reference. Here’s the command I used with SuSiEx. Could you let me know if there are any issues with the syntax or parameters?

```
command <- paste(
    "/share/NCB/CZL/code/SuSiEx_code/SuSiEx-master/bin_static/SuSiEx",
    paste0("--sst_file=", gwas1_temp_name, ",", gwas2_temp_name),
    paste0("--ref_file=", ref1, ",", ref2),
    paste0("--ld_file=", ld1, ",", ld2),
    paste0("--n_gwas=", n1, ",", n2),
    paste0("--out_dir=", out_dir),
    paste0("--out_name=", out_name),
    paste0("--level=0.99"),
    paste0("--pval_thresh=1e-05"),
    paste0("--maf=0.001"),
    paste0("--n_sig=5"),
    paste0("--chr=", chr),
    paste0("--bp=", start, ",", end),
    paste0("--snp_col=1,1"),
    paste0("--chr_col=2,2"),
    paste0("--bp_col=3,3"),
    paste0("--a1_col=4,4"),
    paste0("--a2_col=5,5"),
    paste0("--eff_col=7,7"),
    paste0("--se_col=8,8"),
    paste0("--pval_col=9,9"),
    paste0("--plink=/share/NCB/CZL/code/SuSiEx_code/SuSiEx-master/utilities/plink"),
    paste0("--mult-step=True"),
    paste0("--keep-ambig=True"),
    paste0("--threads=5")
)
system(command)
```

For susieR:

```
if (!any(gwas1_temp$P < 1e-5) & !any(gwas2_temp$P < 1e-5)) {
    next
}
fitted_rss1 <- susie_rss(c(data1_ordered$zscore), ld1, n = median(data1_ordered$N, na.rm = TRUE), L = 5, maf_thresh = 0.001, coverage = 0.99)
```

Also, are you from China? Could I add you on WeChat for further contact?

**Comment by goodluckncb** [comment]
Hi Kai,

Over the past few days, I reanalyzed the results for colorectal cancer and found that susieR detected a greater number of credible sets (CS) at 99% confidence and yielded shorter CS lengths.. Here are the results:

- **SuSiEx**: `table(SuSiEx$CS_LENGTH)`

```
1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  19  20  21  22  23  25  26  27  28  29  32  33  34  35  36  37  38  39  40  50  52  58  68  73  75  76  82  86  95  96  99 106 111 113
42  22  16  20  12   4   7   6   4   4   4   3   2   4   5   1   5   3   4   2   2   2   3   2   1   1   2   1   1   2   1   1   1   1   1   2   1   1   1   2   1   1   1   2   1   1   1   1   1   1
```

- **susieR_EUR**: `table(susieR_EUR$cs_length)`

```
1   2   3   4   5   6   7   8   9  11  12  13  14  15  16  19  21  23  25  28  29
519  53  21   7   7   9   2   3   1   1   1   2   3   1   1   1   1   1   1   1   1
```

- **susieR_EAS**: `table(susieR_EAS$cs_length)`

```
1   2   3   4   5   6   7   8   9  10  11  12  13  14  16  17  19  28  33  35  38  41  80 115
236  40  14   8   4   3   4   6   4   2   1   2   1   1   1   1   1   1   1   1   1   1   1   1
```

Since most of my European and Asian meta-analysis data are derived from individual GWAS data, I used the 1000 Genomes as the LD reference. Here’s the command I used with SuSiEx. Could you let me know if there are any issues with the syntax or parameters?

```
command <- paste(
    "/share/NCB/CZL/code/SuSiEx_code/SuSiEx-master/bin_static/SuSiEx",
    paste0("--sst_file=", gwas1_temp_name, ",", gwas2_temp_name),
    paste0("--ref_file=", ref1, ",", ref2),
    paste0("--ld_file=", ld1, ",", ld2),
    paste0("--n_gwas=", n1, ",", n2),
    paste0("--out_dir=", out_dir),
    paste0("--out_name=", out_name),
    paste0("--level=0.99"),
    paste0("--pval_thresh=1e-05"),
    paste0("--maf=0.001"),
    paste0("--n_sig=5"),
    paste0("--chr=", chr),
    paste0("--bp=", start, ",", end),
    paste0("--snp_col=1,1"),
    paste0("--chr_col=2,2"),
    paste0("--bp_col=3,3"),
    paste0("--a1_col=4,4"),
    paste0("--a2_col=5,5"),
    paste0("--eff_col=7,7"),
    paste0("--se_col=8,8"),
    paste0("--pval_col=9,9"),
    paste0("--plink=/share/NCB/CZL/code/SuSiEx_code/SuSiEx-master/utilities/plink"),
    paste0("--mult-step=True"),
    paste0("--keep-ambig=True"),
    paste0("--threads=5")
)
system(command)
```

For susieR:

```
if (!any(gwas1_temp$P < 1e-5) & !any(gwas2_temp$P < 1e-5)) {
    next
}
fitted_rss1 <- susie_rss(c(data1_ordered$zscore), ld1, n = median(data1_ordered$N, na.rm = TRUE), L = 5, maf_thresh = 0.001, coverage = 0.99)
```

Also, are you from China? Could I add you on WeChat for further contact?

**Comment by goodluckncb** [comment]
To identify candidate regions, I applied the following code:

```r
sig <- data[data$P < 1e-6, ]
distance <- 0.25e6
lead <- get_lead_snps(sig, thresh = 1e-6, region_size = 2 * distance)
```

This allowed me to obtain lead SNPs from three sources: (1) MR-MEGA, (2) EUR (using METAL), and (3) EAS (using METAL). To avoid overlapping regions, I applied the same code again to filter the lead SNPs from these three sources, resulting in a total of 245 lead SNPs. 

For fine-mapping, I set the width of each candidate region to 250 kb upstream and downstream of each lead SNP.

**Comment by yorkklause** [comment]
Hi caibo,

I didn’t fully understand your results on credible set (CS) lengths and how this led to the conclusion that "susieR detected a greater number of credible sets at 99% confidence and yielded shorter CS lengths."

Your results table has two rows—what does each represent?

I assume the first row is a CS identifier or something equivalent. If so, is this ID aligned across the three analyses? For example, does CS 1 represent the same signal in each?

And the second row, I assume, is CS length?

If my assumptions are correct, it actually appears that SuSiEx identified more CSs.


For LD, we recommend using in-sample LD since mismatches between GWAS summary statistics and LD may lead to inflation. In your analysis, obtaining in-sample LD appears challenging, so using a closely related continental population as a reference is acceptable.

For defining loci, we recommend incorporating LD information. In our paper, we used a clumping-based method to define candidate loci, as described in the 'Methods/Biobank Analysis/Loci Definition' section.

My best

Kai Yuan

**Comment by goodluckncb** [comment]
Hi Kai Yuan,

I apologize for any confusion caused. In the data I provided, the first row represents different lengths of credible sets (CS), while the second row indicates the number of CS with each respective length. To clarify further, here’s a specific example:

**Example for region # chr1:70745562-71245562:**

| Method   | CS_ID | CS Length | CS_PURITY | MAX_PIP_SNP       | BP       | REF_ALLELE | ALT_ALLELE | REF_FRQ        | BETA                        | SE                       | LOG10P                  | MAX_PIP   | POST-HOC_PROB_POP1 | POST-HOC_PROB_POP2 |
|----------|-------|-----------|-----------|-------------------|----------|------------|------------|----------------|-----------------------------|--------------------------|-------------------------|-----------|---------------------|---------------------|
| SuSiEx   | 1     | 25        | 0.986484  | 1:67451924:T:G    | 67451924 | G, G       | T, T       | 0.7366, 0.8829 | -0.0120877, -0.00625645     | 0.0021855, 0.00537027    | 7.49668, 0.612588      | 0.0932669 | 0.999706           | 0.340322           |

| Method   | CS_ID | CS log10bf   | CS Length | MAX_PIP_SNP       | CHR | POS      | A1 | A2 | BETA   | SE    | P           | MAX_PIP   |
|----------|-------|--------------|-----------|--------------------|-----|----------|----|----|--------|-------|-------------|-----------|
| susieR   | 1     | 252228.4593  | 2         | 1:67447450:G:A    | 1   | 67447450 | G  | A  | -0.0436 | 0.0081 | 6.619E-08   | 0.749998441 |
| susieR   | 2     | 215419.6318  | 1         | 1:67451924:T:G    | 1   | 67451924 | T  | G  | 0.0448  | 0.0081 | 3.416E-08   | 1           |
| susieR   | 3     | 1607.754246  | 2         | 1:67451924:T:G    | 1   | 67451924 | T  | G  | 0.0448  | 0.0081 | 3.416E-08   | 1           |

---

This example illustrates the results generated by SuSiEx and susieR for credible sets (CS) within this region, including information on CS length, purity, PIP SNPs, and other relevant parameters.

**Comment by goodluckncb** [comment]
The final results for colorectal cancer are as follows:

- Using the SuSiEx method, 210 credible sets (CS) were identified, of which 133 have a length of 10 or fewer, with a median length of 5.
- Using the susieR method on European data, 637 credible sets were identified, of which 622 have a length of 10 or fewer, with a median length of 1.  
 Moreover, when comparing the results from both methods, it appears that **susieR** tends to identify more credible sets (CS) within the same region, whereas **SuSiEx** tends to identify a single, longer CS in that region.

**Comment by yorkklause** [comment]
Hi caibo,

Thank you for clarifying.

In your provided example, the susieR results look unusual:

1. Credible sets 2 and 3 share the same top SNP, 1:67451924:T
2. The two best SNPs, 1:67447450:G and 1:67451924:T, are highly correlated and are completely linked in the 1000 Genomes Project EUR and EAS

I suggest double-checking your LD input for susieR to ensure there is no variant flipping.

My best

Kai Yuan

**Comment by goodluckncb** [comment]
Hi Kai Yuan,
Thank you for your valuable feedback. We will double-check the LD input for susieR to ensure there are no variant-flipping issues and re-examine the data accordingly. We greatly appreciate your insights and will provide an update once we have reviewed the results.

Best regards, Caibo
