### ISSUE TITLE
执行用例错误

### ISSUE THREAD

**Issue by wwhwwxlz** [getian107/SuSiEx#19]
[root@181-12-19-171 examples]# ../bin/SuSiEx --sst_file=EUR.sumstats.txt,AFR.sumstats.txt --n_gwas=50000,50000 --ref_file=EUR,AFR --ld_file=EUR,AFR --out_dir=./ --out_name=SuSiEx.EUR.AFR.output.cs95 --level=0.95 --pval_thresh=1e-5 --maf=0.005 --chr=1 --bp=7314654,8314677 --snp_col=2,2 --chr_col=1,1 --bp_col=3,3 --a1_col=4,4 --a2_col=5,5 --eff_col=6,6 --se_col=7,7 --pval_col=9,9 --plink=../utilities/plink --mult-step=True --keep-ambig=True --threads=16
提示：段错误 (核心已转储)

**Comment by wwhwwxlz** [comment]
cat /proc/version
Linux version 4.19.90-2112.8.0.0131.oe1.aarch64 (abuild@obs-worker-0016) (gcc version 7.3.0 (GCC)) #1 SMP Fri Dec 31 19:53:20 UTC 2021

**Comment by yorkklause** [comment]
Hi wwhwwxlz,

The error message "Segmentation fault (core dumped)" can be caused by various issues. Could you provide more details? Is there any additional information displayed on the screen?

I noticed you're using the SuSiEx from the "bin" folder rather than the "bin_static" folder. Did you compile this script on your machine? If so, please try running:

ldd ../bin/SuSiEx
This command will verify that all necessary dynamic libraries are correctly linked to the script.

Alternatively, in the "bin_static" folder, there's a static version of SuSiEx that can be executed directly on a Linux system. Could you try running that version?

My best

Kai Yuan

**Comment by wwhwwxlz** [comment]
[root@181-12-19-171 bin]# ldd SuSiEx
        linux-vdso.so.1 (0x0000fffcff1b0000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x0000fffcfefe0000)
        libm.so.6 => /lib64/libm.so.6 (0x0000fffcfef10000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x0000fffcfeec0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000fffcfee80000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000fffcfee40000)
        libc.so.6 => /lib64/libc.so.6 (0x0000fffcfecc0000)
        /lib/ld-linux-aarch64.so.1 (0x0000fffcff1c0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000fffcfec90000)

**Comment by wwhwwxlz** [comment]
[root@181-12-19-171 bin_static]# bash SuSiEx
SuSiEx: SuSiEx：无法执行二进制文件

**Comment by yorkklause** [comment]
In the examples folder, you can try this:

../bin_static/SuSiEx --sst_file=EUR.sumstats.txt,AFR.sumstats.txt --n_gwas=50000,50000 --ref_file=EUR,AFR --ld_file=EUR,AFR --out_dir=./ --out_name=SuSiEx.EUR.AFR.output.cs95 --level=0.95 --pval_thresh=1e-5 --maf=0.005 --chr=1 --bp=7314654,8314677 --snp_col=2,2 --chr_col=1,1 --bp_col=3,3 --a1_col=4,4 --a2_col=5,5 --eff_col=6,6 --se_col=7,7 --pval_col=9,9 --plink=../utilities/plink --mult-step=True --keep-ambig=True --threads=16

The file SuSiEx in the bin_static folder is executable. It is not a bash script.

**Comment by wwhwwxlz** [comment]
[root@181-12-19-171 examples]# ../bin_static/SuSiEx --sst_file=EUR.sumstats.txt,AFR.sumstats.txt --n_gwas=50000,50000 --ref_file=EUR,AFR --ld_file=EUR,AFR --out_dir=./ --out_name=SuSiEx.EUR.AFR.output.cs95 --level=0.95 --pval_thresh=1e-5 --maf=0.005 --chr=1 --bp=7314654,8314677 --snp_col=2,2 --chr_col=1,1 --bp_col=3,3 --a1_col=4,4 --a2_col=5,5 --eff_col=6,6 --se_col=7,7 --pval_col=9,9 --plink=../utilities/plink --mult-step=True --keep-ambig=True --threads=16
-bash: ../bin_static/SuSiEx: 权限不够
[root@181-12-19-171 examples]# chmod +x ../bin_static/SuSiEx
[root@181-12-19-171 examples]# ../bin_static/SuSiEx --sst_file=EUR.sumstats.txt,AFR.sumstats.txt --n_gwas=50000,50000 --ref_file=EUR,AFR --ld_file=EUR,AFR --out_dir=./ --out_name=SuSiEx.EUR.AFR.output.cs95 --level=0.95 --pval_thresh=1e-5 --maf=0.005 --chr=1 --bp=7314654,8314677 --snp_col=2,2 --chr_col=1,1 --bp_col=3,3 --a1_col=4,4 --a2_col=5,5 --eff_col=6,6 --se_col=7,7 --pval_col=9,9 --plink=../utilities/plink --mult-step=True --keep-ambig=True --threads=16
-bash: ../bin_static/SuSiEx：无法执行二进制文件: 可执行文件格式错误

**Comment by yorkklause** [comment]
Hi wwhwwxlz,

It appears that your machine is ARM64, while the file ../bin_static/SuSiEx was compiled for x86_64 architecture, so the static version won’t work on your system.

Since you’ve compiled SuSiEx on your machine, it should be compatible. However, plink might be causing the issue.

Could you try running the following command in the examples folder:

../utilities/plink --bfile AFR --keep-allele-order --chr 1 --maf 0.005 --make-bed --out AFR_maf

to make sure plink is OK.

My best

Kai Yuan

**Comment by wwhwwxlz** [comment]
[root@181-12-19-171 examples]# ../utilities/plink --bfile AFR --keep-allele-order --chr 1 --maf 0.005 --make-bed --out AFR_maf
-bash: ../utilities/plink：无法执行二进制文件: 可执行文件格式错误

**Comment by wwhwwxlz** [comment]
哭唧唧

**Comment by yorkklause** [comment]
Ah, I see the issue now... I’m sorry that I can’t assist further, as this appears to be a problem with plink compatibility.

I have two suggestions:

1. Try to find a machine with an x86_64 architecture.
2. Look for a version of plink 1.9 compatible with ARM64, or consider compiling plink directly on your machine.

My best

Kai Yuan

**Comment by yorkklause** [comment]
@wwhwwxlz This post might be helpful if you would like to compile Plink on your machine.

https://github.com/chrchang/plink-ng/issues/253

**Comment by wwhwwxlz** [comment]
good，i will try it

**Comment by wwhwwxlz** [comment]
我已编译好了1.9plink
[root@hostnamelpfy8 examples]# ../utilities/plink --bfile AFR --keep-allele-order --chr 1 --maf 0.005 --make-bed --out AFR_maf
PLINK v1.90p 64-bit (24 Sep 2022)              www.cog-genomics.org/plink/1.9/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to AFR_maf.log.
Options in effect:
  --bfile AFR
  --chr 1
  --keep-allele-order
  --maf 0.005
  --make-bed
  --out AFR_maf

522066 MB RAM detected; reserving 261033 MB for main workspace.
7487 variants loaded from .bim file.
20000 people (0 males, 0 females, 20000 ambiguous) loaded from .fam.
Ambiguous sex IDs written to AFR_maf.nosex .
20000 phenotype values loaded from .fam.
Warning: Ignoring phenotypes of missing-sex samples.  If you don't want those
phenotypes to be ignored, use the --allow-no-sex flag.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 20000 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is exactly 1.
1104 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
6383 variants and 20000 people pass filters and QC.
Among remaining phenotypes, 0 are cases and 20000 are controls.
--make-bed to AFR_maf.bed + AFR_maf.bim + AFR_maf.fam ... done.

**Comment by wwhwwxlz** [comment]
但是执行用例任然报错

**Comment by wwhwwxlz** [comment]
[root@hostnamelpfy8 examples]# ../bin/SuSiEx --sst_file=EUR.sumstats.txt,AFR.sumstats.txt --n_gwas=50000,50000 --ref_file=EUR,AFR --ld_file=EUR,AFR --out_dir=./ --out_name=SuSiEx.EUR.AFR.output.cs95 --level=0.95 --pval_thresh=1e-5 --maf=0.005 --chr=1 --bp=7314654,8314677 --snp_col=2,2 --chr_col=1,1 --bp_col=3,3 --a1_col=4,4 --a2_col=5,5 --eff_col=6,6 --se_col=7,7 --pval_col=9,9 --plink=../utilities/plink --mult-step=True --keep-ambig=True --threads=16
Segmentation fault (core dumped)

**Comment by yorkklause** [comment]
Hi wwhwwxlz,

It looks like you executed "../bin/SuSiEx" on the server "hostnamelpfy8", but compiled it on "181-12-19-171". Could you please recompile SuSiEx directly on "hostnamelpfy8" by running:

make clean
make all

My best

Kai Yuan
