### ISSUE TITLE
Highly Significant Loci

### ISSUE THREAD

**Issue by mconery** [getian107/SuSiEx#2]
Hi SuSiEx Team! We're hoping to use your method to fine-map some highly significant loci where the p-values of association in individual ancestries are < e-325.  I tried to follow your code, and it looks like there are imposed limits on p-values of 1e-323. Is there a reason for this limit? I was under the impression that precision limits for python were already more restrictive than e-323 (2.2e-308). More importantly, will I be able to use SuSiEx on these loci and get reliable results?

**Comment by getian107** [comment]
Hi- Thanks for the question and feedback! The fine-mapping algorithm is based on standardized effect sizes calculated from beta and se. P-values are only used when writing the output file I believe (will double check) and thus do not affect the accuracy of fine-mapping. That said, our experience is that highly significant loci are difficult to fine-map as very small mismatch between summary statistics and the LD reference panel can lead to spurious signals and credible sets. So we would recommend being cautious about this issue and more aggressively filtering out unreasonable results. I would need more time to respond to your other request (more detailed output) and am hoping to get to that in the next couple of weeks.

**Comment by mconery** [comment]
Thanks for getting back to me so quickly! That sounds good regarding the highly significant loci and the more detailed output. We were already planning on using in-sample LD for our analysis to hopefully minimize the spurious signals you mentioned, and had planned to do aggressive manual filtering of these loci.  Thank you again!
