### ISSUE TITLE
Effect sizes exactly equal to zero in GWAS sumstats exits SuSieX with "Error: Effect size of Line XXXX is not a number (NAN)"

### ISSUE THREAD

**Issue by AmeliaES** [getian107/SuSiEx#20]
Hi Kai Yuan and Tian Ge, thanks for making such a great piece of software for fine mapping analysis across different ancestries. I've just started using SuSiEx for some analysis and have run into an error I wondered if you could help advise me with please.

"Error: Effect size of Line 28807 is not a number (NAN)
rs12728576	G	T	0.555608	0	0	0.9957	346840	1	7399646	289533
BETA/OR: 0
SE: 0"

This error occurs because one of the GWAS sumstats files parsed to ` --sst_file` contains the value zero for the BETA and SE columns. If I remove all rows where zero occurs in the BETA column this error does not occur and SuSiEx runs to completion. I wondered what your advice for this would be - should I remove all rows in my GWAS sumstats files where the effect size is zero? Or would this cause some sort of bias? 

If it's helpful I can also provide the full log and/or some dummy data to reproduce this error.
I'm running SuSiEx on Rocky Linux (version 9.4)

Many thanks,
Amelia

**Comment by yorkklause** [comment]
Hi Amelia,

Thank you for using our software!

For the issue you're encountering, I recommend removing variants where SE == 0, rather than those with BETA values. In SuSiEx, we incorporate BETA/SE into our model, and when SE == 0, the BETA/SE ratio becomes undefined (NaN).

Let me know if you have any further questions!

My best

Kai Yuan

**Comment by AmeliaES** [comment]
Hi Kai, 
Thanks very much for your quick response and helpful advice. I shall remove rows where the standard error equals zero. 
Many thanks,
Amelia
