### ISSUE TITLE
Fine-Mapping including Indels

### ISSUE THREAD

**Issue by GHawkes93** [getian107/SuSiEx#3]
Hi,

Thanks for making this software - it is really useful.

I'm currently attempting to fine-map using some whole-genome sequencing data, meaning that I've used the same dataset for my association testing and reference genetic data. However, I've noticed that your script seems to exclude indels during the alignment step if the alleles are not ['A', 'C', 'G', 'T'] - is this necessary? Could there be support for indels, or does this have other unintended downstream consequences?

Thanks for your time,
Gareth

**Comment by getian107** [comment]
Hi Gareth- Thanks for the question! You are right that this is one limitation of SuSiEx. As we discussed in the preprint, currently we restrict the analyses to SNPs to avoid potential strand flips and alignment errors when analyzing indels across
datasets, which may produce false positives if fine-mapped SNP(s) are proxies for causal indels or structural variations. We are hoping to improve the tool and properly incorporate indels in fine-mapping in a future release.

**Comment by GHawkes93** [comment]
I have made some edits to the script which I think will allow indels to work... Hopefully I haven't broken anything!

Good to know its on your radar.

**Comment by getian107** [comment]
I think it's fine to simply remove the ATCG restriction if data quality is ensured (e.g., homogeneous cohorts or identical reference panels). It's a bit tricky to align indels across datasets that have different reference panels and/or different ways to code indels, which we will try to fix.

**Comment by yorkklause** [comment]
Hi GHawkes93,
we have recently released an updated version of SuSiEx, now implemented in C++. In this new version, we have enabled the indels input.
Kai
