### ISSUE TITLE
The column naming rules are too strict.

### ISSUE THREAD

**Issue by hanbin973** [getian107/SuSiEx#5]
Hi, thanks for the great software. 
I just have a suggestion regarding the input format.

In `parse_genet.py `line 157 to 161
```
158                     if header[eff_col-1] == 'BETA':
159                         beta = float(ll[eff_col-1])
160                     elif header[eff_col-1] == 'OR':
161                         beta = sp.log(float(ll[eff_col-1]))
```
restricts the eff size column to be either BETA or OR. 
The column names could be often in lower case or have different names.
If the column name doesn't match either words, it returns an error
```
Traceback (most recent call last):
  File "/data02/hanbin973/susiex/SuSiEx/SuSiEx.py", line 232, in <module>
    main()
  File "/data02/hanbin973/susiex/SuSiEx/SuSiEx.py", line 175, in main
    sst_dict[pp] = parse_genet.parse_sumstats(param_dict['sst_file'][pp], ref_dict[pp], param_dict['chr'], param_dict['bp'],
  File "/data02/hanbin973/susiex/SuSiEx/parse_genet.py", line 167, in parse_sumstats
    sst_eff.update({snp: beta/se/n_sqrt})
UnboundLocalError: local variable 'beta' referenced before assignment
```
As my summary statistics are combined in a single file, mine has names 'BETA1', 'BETA2', 'BETA3', ... so on.
For my purpose I slightly changed the lines to 
```
158                     if 'BETA' in header[eff_col-1]:
159                         beta = float(ll[eff_col-1])
160                     elif 'OR' in header[eff_col-1]:
161                         beta = sp.log(float(ll[eff_col-1]))
```
so that it handles the column names properly.

It would be better to have additional options to the script that accepts how the effect size is stored or that accepts custom names of the headers. 

Thx.

**Comment by getian107** [comment]
Thanks for the suggestions! We are currently improving the software including shifting to a C++ implementation with more features requested by the users. We will try to incorporate your suggestions in the next release.

**Comment by yorkklause** [comment]
Hi hanbin973, 
We have recently released an updated version of SuSiEx, which has been implemented in C++. We have addressed the issue you encountered with the column name requirement. SuSiEx now accepts column names with the "BETA" or "OR" prefix.
