### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by privefl** [getian107/SuSiEx#8]
I'm trying to run SuSiEx with 5 different populations.

This is my call
![SuSiEx-call](https://github.com/getian107/SuSiEx/assets/11161036/9228083c-ace8-42b3-a4e1-256dec00a343)

And one of the sumstats file I'm using (tab delimited)
![SuSiEx-sst](https://github.com/getian107/SuSiEx/assets/11161036/0204e6d5-176b-4031-86e5-30e8273c28ef)

**Is there any obvious issue to you?**

**Comment by yorkklause** [comment]
Hi privefl,

Thank you for reporting the bug!

I recently encountered a segmentation fault that may be related to the issue you mentioned. 

This error occurred while analyzing loci with multiple causal signals using the "--mult-step" fitting procedure. 

Specifically, the error occurred at the end of the iteration. I have addressed and fixed this problem. Could you download the latest version and try again?

My best

Kai Yuan

**Comment by privefl** [comment]
I don't think I'm using `--mult-step` and the program stops very quickly (after like 1-2 sec).

**Comment by yorkklause** [comment]
Hi privefl,

The "--mult-step" option will be enabled by default unless explicitly turned off. 
Could you provide the screen output log?

Kai Yuan

**Comment by privefl** [comment]
I do not get any output log, I directly get the segmentation fault.

**Comment by yorkklause** [comment]
Can you obtain results with the example data?

**Comment by privefl** [comment]
I get this when running the example code
![susiex-examples](https://github.com/getian107/SuSiEx/assets/11161036/9318c611-467f-4842-9141-025947f0c272)

**Comment by yorkklause** [comment]
Could you please ensure that you compile SuSiEx and run it in the same environment? 
It appears that the software has been compiled with a higher version of the stdc++ library.
You can run

```
cd src
make clean
make all
```

to re-compile the software.

**Comment by privefl** [comment]
I think that works now, thanks.

I also ran `conda install libgcc`, not sure if that helped as well.
(cf. https://askubuntu.com/a/786944)
